title:
logo: /assets/img/logo.png
description:
show_downloads: true
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins: [jekyll-remote-theme] # add this line to the plugins list if you already have one
github:
  repository_url: "https://github.com/patrickjohncyh"
  icon: /assets/img/github.png
linkedin:
  profile_url: "https://www.linkedin.com/in/patrick-john-chia/"
  icon: /assets/img/linkedin.png
gscholar:
  url: "https://scholar.google.ca/citations?hl=en&user=6nJbjacAAAAJ"
  icon: /assets/img/gscholar.png
publications:
  natureevalrs:
    author: Tagliabue et al.
    year: 2023
    title: "A challenge for rounded evaluation of recommender systems"
    venue: Nature Machine Intelligence
    url: "https://www.nature.com/articles/s42256-022-00606-0"
  fashionclip:
    author: Chia et al.
    year: 2022
    title: Contrastive language and vision learning of general fashion concepts
    venue: Nature Scientific Reports
    url: "https://www.nature.com/articles/s41598-022-23052-9"
  evalrs:
    author: Tagliabue et al.
    year: 2022
    title: "EvalRS: a Rounded Evaluation of Recommender Systems"
    venue: arXiv Preprint
    url: "https://arxiv.org/abs/2207.05772"
  gradrec:
    author: Chia et al.
    year: 2022
    title: \"Does it come in black?\" CLIP-like models are zero-shot recommenders
    venue: ECNLP5 ACL'22
    url: "https://aclanthology.org/2022.ecnlp-1.22/"
  reclist:
    author: Chia et al.
    year: 2022
    title: "Beyond NDCG : behavioral testing of recommender systems with RecList"
    venue: TheWebConf'22
    url: "https://dl.acm.org/doi/10.1145/3487553.3524215"
  sigirdata:
      author: Tagliabue et al.
      year: 2021
      title: "Sigir 2021 e-commerce workshop data challenge"
      venue: arXiv Preprint
      url: "https://arxiv.org/abs/2104.09423"
  prodcomparison:
    author: Chia et al.
    year: 2021
    title: "\"Are you sure?\": Preliminary Insights from Scaling Product Comparisons to Multiple Shops"
    venue: SIGIR eCom’21
    url: "https://sigir-ecom.github.io/ecom21Papers/paper15.pdf"